// =============================================
// Demo / Seed Data — Works without Supabase
// Rich tactical product catalog for demo mode
// =============================================

import type {
  Product, Category, Order, OrderItem, Profile,
  AuditLog, SystemAlert, PaymentVerification, Notification,
  DailySalesSummary, ProductSalesSummary, CategorySalesSummary,
  ShippingZone, DriverEarning, DriverAvailability, FixedAmountQR,
  PaymentGatewaySettings
} from './types';

// ============ CATEGORIES ============
export const demoCategories: Category[] = [
  { id: 'cat-01', name: 'Chalecos Tácticos', slug: 'chalecos-tacticos', description: 'Chalecos antibalas, porta-placas y plate carriers de grado militar', parent_id: null, position: 1, is_active: true, created_at: '2026-01-15T10:00:00Z' },
  { id: 'cat-02', name: 'Calzado Táctico', slug: 'calzado-tactico', description: 'Botas militares, de combate y operativas de alto rendimiento', parent_id: null, position: 2, is_active: true, created_at: '2026-01-15T10:00:00Z' },
  { id: 'cat-03', name: 'Óptica & Linternas', slug: 'optica-linternas', description: 'Miras holográficas, linternas tácticas y lentes balísticos UV400', parent_id: null, position: 3, is_active: true, created_at: '2026-01-15T10:00:00Z' },
  { id: 'cat-04', name: 'Mochilas & Morrales', slug: 'mochilas-morrales', description: 'Mochilas militares de asalto, morrales bandolera y pecheras tácticas MOLLE', parent_id: null, position: 4, is_active: true, created_at: '2026-01-15T10:00:00Z' },
  { id: 'cat-05', name: 'Accesorios Tácticos', slug: 'accesorios-tacticos', description: 'Guantes de combate, rodilleras, cascos FAST, fundas portapistolas y cinturones', parent_id: null, position: 5, is_active: true, created_at: '2026-01-15T10:00:00Z' },
  { id: 'cat-06', name: 'Cuchillería Táctica', slug: 'cuchilleria', description: 'Cuchillos de combate, navajas tácticas y herramientas de supervivencia militar', parent_id: null, position: 6, is_active: true, created_at: '2026-01-15T10:00:00Z' },
  { id: 'cat-07', name: 'Relojes & Telecom', slug: 'relojes-telecom', description: 'Relojes tácticos digitales impermeables, radios bidireccionales y comunicadores', parent_id: null, position: 7, is_active: true, created_at: '2026-01-15T10:00:00Z' },
  { id: 'cat-08', name: 'Vestimenta Táctica', slug: 'vestimenta-tactica', description: 'Pantalones cargo ripstop, poleras de combate (combat shirts) y uniformes militares', parent_id: null, position: 8, is_active: true, created_at: '2026-01-15T10:00:00Z' },
];

// ============ DEFAULT STORE SETTINGS (COCHABAMBA, BOLIVIA) ============
export const defaultStoreSettings = {
  storeName: 'Tienda Táctica Cochabamba',
  currency: 'BOB',
  currencySymbol: 'Bs.',
  pickupAddress: 'Av. Heroínas #560 entre San Martín y 25 de Mayo, Zona Central, Cochabamba',
  pickupSchedule: 'Lunes a Sábado de 09:00 a 19:00 (Horario Continuo)',
  pickupInstructions: 'Presentar carnet de identidad o el código de tu orden al momento del recojo en nuestro almacén central de Cochabamba.',
  freeGiftName: 'Pack de Stickers Tácticos Exclusivos (Edición Especial — ¡Descúbrelos al recibir tu paquete!)',
  freeGiftValue: 35.00,
};

// ============ DEFAULT PAYMENT GATEWAY SETTINGS (YAPE BOLIVIA / BCP) ============
export const defaultPaymentGatewaySettings: PaymentGatewaySettings = {
  active_provider: 'yape',
  provider_name: 'Yape Bolivia / BCP Soli',
  package_name: 'com.bcp.bo.wallet',
  account_holder: 'Tienda Táctica Bolivia SRL',
  phone_or_account: '78353814',
  checkout_title: 'Pago Rápido con Yape Bolivia (Simple QR)',
  checkout_instructions: 'Escanea el código QR táctico directamente desde tu aplicación Yape o BCP. Al confirmar en tu celular, el pago se acredita en tiempo real sin necesidad de enviar comprobantes manuales.',
  auto_match_enabled: true,
  notify_on_verified: true,
  updated_at: new Date().toISOString(),
};

// ============ SHIPPING ZONES (COCHABAMBA & NACIONAL) ============
export const demoShippingZones: ShippingZone[] = [
  { id: 'zone-01', name: 'Cochabamba — Centro / Casco Viejo / Las Cuadras / San Pedro (Delivery)', department: 'Cochabamba', city: 'Cochabamba', shipping_cost: 12.00, driver_commission: 8.00, store_profit: 4.00, estimated_hours: 2, is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'zone-02', name: 'Cochabamba — Zona Norte (Cala Cala, Queru Queru, Av. América, Tupuraya)', department: 'Cochabamba', city: 'Cochabamba', shipping_cost: 15.00, driver_commission: 10.00, store_profit: 5.00, estimated_hours: 3, is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'zone-03', name: 'Cochabamba — Zona Sur (Jaihuayco, Lacma, La Chimba, Albarrancho)', department: 'Cochabamba', city: 'Cochabamba', shipping_cost: 15.00, driver_commission: 10.00, store_profit: 5.00, estimated_hours: 3, is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'zone-04', name: 'Cochabamba Metropolitana — Quillacollo y Colcapirhua (Delivery Express)', department: 'Cochabamba', city: 'Quillacollo', shipping_cost: 20.00, driver_commission: 15.00, store_profit: 5.00, estimated_hours: 4, is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'zone-05', name: 'Cochabamba Metropolitana — Sacaba (Delivery Express)', department: 'Cochabamba', city: 'Sacaba', shipping_cost: 20.00, driver_commission: 15.00, store_profit: 5.00, estimated_hours: 4, is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'zone-06', name: 'Cochabamba Metropolitana — Tiquipaya (Delivery Express)', department: 'Cochabamba', city: 'Tiquipaya', shipping_cost: 18.00, driver_commission: 13.00, store_profit: 5.00, estimated_hours: 4, is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'zone-07', name: 'Envío Nacional Flota — Desde Terminal de Buses Cbba (La Paz, Santa Cruz, Oruro, Sucre, Tarija, Potosí, Beni, Pando)', department: 'Nacional', city: 'Terminal Cochabamba', shipping_cost: 35.00, driver_commission: 25.00, store_profit: 10.00, estimated_hours: 24, is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'zone-08', name: 'Envío Nacional Courier — Shalom / Expreso a Domicilio desde Cochabamba', department: 'Nacional', city: 'Bolivia Courier', shipping_cost: 40.00, driver_commission: 28.00, store_profit: 12.00, estimated_hours: 48, is_active: true, created_at: '2026-01-01T00:00:00Z' },
];

// ============ DEMO PROFILES (ADMIN, DRIVERS, CLIENTS - BOLIVIA) ============
export const demoAdmin: Profile = {
  id: 'admin-01', email: 'admin@tacticos.bo', full_name: 'Comandante Dueño', phone: '+591 71234567', avatar_url: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z'
};

export const demoVendor: Profile = {
  id: 'vendor-01', email: 'driver1@tacticos.bo', full_name: 'Carlos Mendoza (Driver Táctico)', phone: '+591 76543210', avatar_url: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z'
};

export const demoDrivers: Profile[] = [
  demoVendor,
  { id: 'driver-02', email: 'driver2@tacticos.bo', full_name: 'Marcos Rivas (Motorizado Alfa)', phone: '+591 79876543', avatar_url: null, created_at: '2026-02-15T00:00:00Z', updated_at: '2026-02-15T00:00:00Z' },
];

export const demoClient: Profile = {
  id: 'client-01', email: 'cliente@tacticos.bo', full_name: 'Juan Operativo', phone: '+591 75512345', avatar_url: null, created_at: '2026-06-01T00:00:00Z', updated_at: '2026-06-01T00:00:00Z'
};

// ============ PRODUCTS ============
export const demoProducts: Product[] = [
  {
    id: 'prod-01',
    name: 'Plate Carrier Táctico Nivel IV Multicam',
    slug: 'plate-carrier-tactico-nivel-iv-multicam',
    description: 'Chaleco porta-placas táctico de combate con sistema MOLLE integral de corte láser. Compatible con placas balísticas Stand-Alone NIJ IV. Hebillas de liberación rápida Cobra, ajuste lumbar acolchado y tejido Cordura 1000D repelente al agua.',
    price: 340.00,
    cost_price: 250.00,
    stock: 14,
    low_stock_threshold: 3,
    category_id: 'cat-01',
    images: ['https://images.unsplash.com/photo-1784612207661-f0deb9ce0223?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-09-15T10:00:00Z',
    deleted_at: null,
    category: demoCategories[0]
  },
  {
    id: 'prod-02',
    name: 'Botas Tácticas Militares Desert Storm Vibram',
    slug: 'botas-tacticas-militares-desert-storm-vibram',
    description: 'Botas de combate militar de 8 pulgadas con suela antideslizante tipo Vibram con autolimpieza. Membrana impermeable y transpirable, puntera reforzada balística vulcanizada y cierre lateral táctico reforzado.',
    price: 310.00,
    cost_price: 220.00,
    stock: 20,
    low_stock_threshold: 5,
    category_id: 'cat-02',
    images: ['https://images.unsplash.com/photo-1601175750527-88def4365509?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-03-05T10:00:00Z',
    updated_at: '2026-09-10T10:00:00Z',
    deleted_at: null,
    category: demoCategories[1]
  },
  {
    id: 'prod-03',
    name: 'Mira Holográfica Táctica EOTech XPS3',
    slug: 'mira-holografica-tactica-eotech-xps3',
    description: 'Mira holográfica militar de punto rojo con retícula perimetral de 68 MOA y punto de 1 MOA. 10 niveles compatibles con visión nocturna NVG, sumergible hasta 10m y cuerpo mecanizado en aluminio aeroespacial 7075-T6.',
    price: 380.00,
    cost_price: 280.00,
    stock: 8,
    low_stock_threshold: 2,
    category_id: 'cat-03',
    images: ['https://images.unsplash.com/photo-1784612212663-716f0518783d?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-03-10T10:00:00Z',
    updated_at: '2026-09-12T10:00:00Z',
    deleted_at: null,
    category: demoCategories[2]
  },
  {
    id: 'prod-04',
    name: 'Mochila Táctica Militar 45L MOLLE Assault Pack',
    slug: 'mochila-tactica-militar-45l-molle-assault-pack',
    description: 'Mochila de asalto y patrulla táctica de 45 litros fabricada en nylon Cordura 1000D de alta tenacidad. Compartimento posterior para bolsa de hidratación 3L, 4 amplios bolsillos con cierres dobles silenciosos y cinchas de compresión militar.',
    price: 220.00,
    cost_price: 140.00,
    stock: 28,
    low_stock_threshold: 5,
    category_id: 'cat-04',
    images: ['https://images.unsplash.com/photo-1707264848832-a1de98edb85c?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
    deleted_at: null,
    category: demoCategories[3]
  },
  {
    id: 'prod-05',
    name: 'Guantes Tácticos de Combate con Nudillos de Carbono',
    slug: 'guantes-tacticos-combate-nudillos-carbono',
    description: 'Guantes tácticos de intervención rápida con carcasa anatómica de fibra de carbono para máxima protección de nudillos. Palma acolchada antideslizante con refuerzo Kevlar, tejido transpirable y puntas táctiles capacitivas para smartphones y GPS.',
    price: 120.00,
    cost_price: 65.00,
    stock: 45,
    low_stock_threshold: 10,
    category_id: 'cat-05',
    images: ['https://images.unsplash.com/photo-1566566716921-b50e82140547?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-04-01T10:00:00Z',
    updated_at: '2026-09-05T10:00:00Z',
    deleted_at: null,
    category: demoCategories[4]
  },
  {
    id: 'prod-06',
    name: 'Cuchillo Táctico Militar de Supervivencia KA-BAR',
    slug: 'cuchillo-tactico-militar-supervivencia-kabar',
    description: 'Cuchillo de combate y supervivencia de hoja enteriza con acero al carbono 1095 Cro-Van de 7 pulgadas. Tratamiento de recubrimiento epoxi antirreflejo negro, pomo rompe-cristales y funda rígida Kydex de retención positiva para acople a cinto o chaleco.',
    price: 150.00,
    cost_price: 85.00,
    stock: 18,
    low_stock_threshold: 3,
    category_id: 'cat-06',
    images: ['https://images.unsplash.com/photo-1773875342538-a45969eb78e5?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-04-10T10:00:00Z',
    updated_at: '2026-09-01T10:00:00Z',
    deleted_at: null,
    category: demoCategories[5]
  },
  {
    id: 'prod-07',
    name: 'Radio Táctico Baofeng UV-5R Militar VHF/UHF',
    slug: 'radio-tactico-baofeng-uv5r-militar',
    description: 'Radio transceptor bidireccional dual-band VHF/UHF con 128 canales de memoria programables y pantalla LCD retroiluminada. Potencia 5W para alcance operativo de hasta 8km. Incluye auricular táctico encubierto con tubo acústico de silicona y antena extendida.',
    price: 150.00,
    cost_price: 90.00,
    stock: 35,
    low_stock_threshold: 8,
    category_id: 'cat-07',
    images: ['https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-04-15T10:00:00Z',
    updated_at: '2026-08-28T10:00:00Z',
    deleted_at: null,
    category: demoCategories[6]
  },
  {
    id: 'prod-08',
    name: 'Pantalón Cargo Táctico Ripstop Antidesgarro',
    slug: 'pantalon-cargo-tactico-ripstop-antidesgarro',
    description: 'Pantalón operativo militar confeccionado en tela Ripstop cuadrícula antidesgarro con tratamiento hidrofóbico antimanchas. 10 bolsillos funcionales organizadores, bolsillos internos para rodilleras tácticas, pretina elástica y costuras dobles reforzadas.',
    price: 200.00,
    cost_price: 130.00,
    stock: 40,
    low_stock_threshold: 8,
    category_id: 'cat-08',
    images: ['https://images.unsplash.com/photo-1776687773939-348819a9b787?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-04-20T10:00:00Z',
    updated_at: '2026-08-25T10:00:00Z',
    deleted_at: null,
    category: demoCategories[7]
  },
  {
    id: 'prod-09',
    name: 'Polera Táctica Militar de Combate (Combat Shirt Ripstop)',
    slug: 'polera-tactica-militar-combate-shirt',
    description: 'Camisa polera táctica de combate militar diseñada para uso cómodo y ventilado bajo chalecos porta-placas. Torso elástico de algodón y elastano de alta transpirabilidad y mangas en tejido Ripstop antidesgarro con bolsillos de hombro con velcro para insignias.',
    price: 145.00,
    cost_price: 85.00,
    stock: 38,
    low_stock_threshold: 6,
    category_id: 'cat-08',
    images: ['https://images.unsplash.com/photo-1764054059763-25078e72f049?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-05-01T10:00:00Z',
    updated_at: '2026-09-18T10:00:00Z',
    deleted_at: null,
    category: demoCategories[7]
  },
  {
    id: 'prod-10',
    name: 'Reloj Militar Táctico Digital G-Shock Impermeable 200M',
    slug: 'reloj-militar-tactico-digital-g-shock-200m',
    description: 'Reloj de operaciones especiales militar con estructura de protección contra impactos extremos y sumergible a 200 metros (20 BAR). Pantalla digital de alto contraste con luz electroluminiscente nocturna, cronómetro 1/100s, alarma y cristal mineral ultra endurecido.',
    price: 180.00,
    cost_price: 110.00,
    stock: 25,
    low_stock_threshold: 5,
    category_id: 'cat-07',
    images: ['https://images.unsplash.com/photo-1576420469891-b303889e81bf?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-05-05T10:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
    deleted_at: null,
    category: demoCategories[6]
  },
  {
    id: 'prod-11',
    name: 'Lentes Balísticos Tácticos UV400 Antirreflejo (3 Cristales)',
    slug: 'lentes-balisticos-tacticos-uv400-3-cristales',
    description: 'Gafas de tiro y patrulla táctica militar con certificación balística contra esquirlas e impactos de alta velocidad. Marco envolvente de polímero liviano resistente, almohadillas nasales de goma antideslizante y 3 juegos de micas intercambiables (negra polarizada, amarilla y clara).',
    price: 115.00,
    cost_price: 60.00,
    stock: 50,
    low_stock_threshold: 10,
    category_id: 'cat-03',
    images: ['https://images.unsplash.com/photo-1708799366365-a24608103bed?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-05-08T10:00:00Z',
    updated_at: '2026-09-18T10:00:00Z',
    deleted_at: null,
    category: demoCategories[2]
  },
  {
    id: 'prod-12',
    name: 'Morral Táctico Bandolera Cruzado MOLLE (Pechera Táctica)',
    slug: 'morral-tactico-bandolera-cruzado-molle',
    description: 'Morral bandolera de asalto urbano y transporte táctico diario EDC. Correa de hombro acolchada ergonómica con enganche ambidiestro, frontal cortado en láser con sistema MOLLE, compartimento secreto de apertura rápida y tejido Oxford 900D impermeable.',
    price: 130.00,
    cost_price: 70.00,
    stock: 35,
    low_stock_threshold: 6,
    category_id: 'cat-04',
    images: ['https://images.unsplash.com/photo-1673505379702-870e878f736a?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-05-10T10:00:00Z',
    updated_at: '2026-09-19T10:00:00Z',
    deleted_at: null,
    category: demoCategories[3]
  },
  {
    id: 'prod-13',
    name: 'Casco Táctico FAST Militar con Rieles y Montura NVG',
    slug: 'casco-tactico-fast-militar-rieles-nvg',
    description: 'Casco táctico de protección balística y anti-impacto tipo FAST PJ con rieles laterales ARC para acople de linternas, auriculares o cámaras y montura frontal reforzada para visores nocturnos NVG. Sistema interno de dial de ajuste rápido de nuca y almohadillas acolchadas.',
    price: 250.00,
    cost_price: 170.00,
    stock: 15,
    low_stock_threshold: 3,
    category_id: 'cat-05',
    images: ['https://images.unsplash.com/photo-1788328358240-f3492c960317?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-05-12T10:00:00Z',
    updated_at: '2026-09-19T10:00:00Z',
    deleted_at: null,
    category: demoCategories[4]
  },
  {
    id: 'prod-14',
    name: 'Kit de Rodilleras y Coderas Tácticas de Alto Impacto',
    slug: 'kit-rodilleras-coderas-tacticas-alto-impacto',
    description: 'Kit de protección táctica militar articulada incluye 2 rodilleras y 2 coderas de alta densidad. Carcasa exterior curva en polímero TPU resistente a rasguños y golpes en roca o pavimento, interior de espuma EVA y correas elásticas con ajuste de velcro rápido.',
    price: 105.00,
    cost_price: 55.00,
    stock: 40,
    low_stock_threshold: 8,
    category_id: 'cat-05',
    images: ['https://images.unsplash.com/photo-1788328395746-2334ab47609a?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-05-14T10:00:00Z',
    updated_at: '2026-09-19T10:00:00Z',
    deleted_at: null,
    category: demoCategories[4]
  },
  {
    id: 'prod-15',
    name: 'Funda Táctica Portapistola Universal (Holster) con Retención',
    slug: 'funda-tactica-portapistola-holster-retencion',
    description: 'Funda pistolera táctica para cinto o plataforma MOLLE con mecanismo de retención activa mediante liberación por dedo índice. Desenfunde suave en 0.3 segundos, ajuste de presión por tornillo y rotación de 360 grados. Compatible con Glock, Bersa, Taurus, CZ y Beretta.',
    price: 100.00,
    cost_price: 50.00,
    stock: 30,
    low_stock_threshold: 6,
    category_id: 'cat-05',
    images: ['https://images.unsplash.com/photo-1786427556258-d8f8d7f08e80?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-05-16T10:00:00Z',
    updated_at: '2026-09-19T10:00:00Z',
    deleted_at: null,
    category: demoCategories[4]
  },
  {
    id: 'prod-16',
    name: 'Chaleco Táctico Ligero MOLLE Modular con Porta-Cargadores',
    slug: 'chaleco-tactico-ligero-molle-modular',
    description: 'Chaleco de intervención táctica liviano y ventilado fabricado en malla reforzada transpirable. Incluye triple pouch porta-cargador elástico frontal, panel frontal de velcro para parches de identificación y sistema MOLLE total delantero y posterior para accesorios adicionales.',
    price: 190.00,
    cost_price: 120.00,
    stock: 25,
    low_stock_threshold: 5,
    category_id: 'cat-01',
    images: ['https://images.unsplash.com/photo-1784612185593-0324d646cdff?w=800&auto=format&fit=crop&q=80'],
    vendor_id: 'vendor-01',
    is_active: true,
    created_at: '2026-05-18T10:00:00Z',
    updated_at: '2026-09-19T10:00:00Z',
    deleted_at: null,
    category: demoCategories[0]
  },
];

// ============ ORDERS ============
const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const demoDriverEarnings: DriverEarning[] = [
  { id: 'earn-01', driver_id: 'vendor-01', order_id: 'ord-001', amount: 10.00, zone_id: 'zone-01', status: 'paid', paid_at: daysAgo(20), created_at: daysAgo(24) },
  { id: 'earn-02', driver_id: 'vendor-01', order_id: 'ord-002', amount: 10.00, zone_id: 'zone-01', status: 'paid', paid_at: daysAgo(15), created_at: daysAgo(21) },
  { id: 'earn-03', driver_id: 'vendor-01', order_id: 'ord-006', amount: 15.00, zone_id: 'zone-02', status: 'pending', paid_at: null, created_at: daysAgo(6) },
];

export const demoOrders: Order[] = [
  {
    id: 'ord-001',
    user_id: 'client-01',
    vendor_id: 'vendor-01',
    driver_id: 'vendor-01',
    shipping_zone_id: 'zone-01',
    shipping_cost: 12.00,
    driver_commission: 8.00,
    status: 'delivered',
    total: 366.98,
    payment_method: 'qr',
    qr_code_data: null,
    created_at: daysAgo(28),
    paid_at: daysAgo(28),
    delivered_at: daysAgo(24),
    cancelled_at: null,
    cancellation_reason: null,
    internal_notes: null,
    customer_name: 'Juan Operativo',
    customer_phone: '+591 75512345',
    customer_email: 'cliente@tacticos.bo',
    customer_address: 'Av. América Este #820 esq. Pando, Edif. Torre Norte Dpto 4B, Cala Cala, Cochabamba',
    delivery_notes: 'Dejar en recepción del edificio a nombre de Juan.',
    customer_rating: 5,
    customer_review: '¡Entrega táctica impecable y súper rápida en Cala Cala! El repartidor fue muy amable.'
  },
  {
    id: 'ord-002',
    user_id: 'client-01',
    vendor_id: 'vendor-01',
    driver_id: 'vendor-01',
    shipping_zone_id: 'zone-01',
    shipping_cost: 12.00,
    driver_commission: 8.00,
    status: 'delivered',
    total: 611.99,
    payment_method: 'qr',
    qr_code_data: null,
    created_at: daysAgo(25),
    paid_at: daysAgo(25),
    delivered_at: daysAgo(21),
    cancelled_at: null,
    cancellation_reason: null,
    internal_notes: null,
    customer_name: 'Juan Operativo',
    customer_phone: '+591 75512345',
    customer_email: 'cliente@tacticos.bo',
    customer_address: 'Calle Baptista #340 esq. Mayor Rocha, Zona Central, Cochabamba',
    delivery_notes: null,
    customer_rating: 5,
    customer_review: 'Todo excelente, paquete blindado y bien protegido.'
  },
  {
    id: 'ord-003',
    user_id: 'client-01',
    vendor_id: 'vendor-01',
    driver_id: 'vendor-01',
    shipping_zone_id: 'zone-04',
    shipping_cost: 20.00,
    driver_commission: 15.00,
    status: 'in_transit',
    total: 214.98,
    payment_method: 'cash_on_delivery',
    qr_code_data: null,
    created_at: daysAgo(1),
    paid_at: null,
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    internal_notes: 'Repartidor en ruta hacia Quillacollo.',
    customer_name: 'Santiago Bravo',
    customer_phone: '+591 76598765',
    customer_email: 'santiago@tacticos.bo',
    customer_address: 'Av. Blanco Galindo Km 11, acera sur, Quillacollo, Cochabamba',
    delivery_notes: 'Cobrar Bs. 214.98 en efectivo o QR al entregar.',
    customer_rating: null,
    customer_review: null
  },
  {
    id: 'ord-004',
    user_id: 'client-01',
    vendor_id: 'vendor-01',
    driver_id: 'vendor-01',
    shipping_zone_id: 'zone-02',
    shipping_cost: 15.00,
    driver_commission: 10.00,
    status: 'picked_up',
    total: 144.99,
    payment_method: 'qr',
    qr_code_data: null,
    created_at: daysAgo(2),
    paid_at: daysAgo(2),
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    internal_notes: 'Pedido recogido de almacén central de Av. Heroínas por Carlos.',
    customer_name: 'Renzo Palacios',
    customer_phone: '+591 78911223',
    customer_email: 'renzo@gmail.com',
    customer_address: 'Av. Libertador Bolívar #1420, Condominio Sarco, Cochabamba',
    delivery_notes: 'Llamar al número antes de ingresar al condominio.',
    customer_rating: null,
    customer_review: null
  },
  {
    id: 'ord-005',
    user_id: 'client-01',
    vendor_id: null,
    driver_id: null,
    shipping_zone_id: 'zone-01',
    shipping_cost: 12.00,
    driver_commission: 8.00,
    status: 'ready',
    total: 101.99,
    payment_method: 'qr',
    qr_code_data: null,
    created_at: daysAgo(1),
    paid_at: daysAgo(1),
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    internal_notes: 'Empacado y listo para retiro en centro de distribución Heroínas.',
    customer_name: 'Carlos Villarroel',
    customer_phone: '+591 71133557',
    customer_email: 'carlos.v@tacticos.bo',
    customer_address: 'Av. Heroínas #560 entre San Martín y 25 de Mayo (Retiro en Tienda), Cochabamba',
    delivery_notes: 'Retira personalmente en almacén central de Cochabamba.',
    customer_rating: null,
    customer_review: null
  },
  {
    id: 'ord-006',
    user_id: 'client-01',
    vendor_id: 'vendor-01',
    driver_id: 'vendor-01',
    shipping_zone_id: 'zone-05',
    shipping_cost: 20.00,
    driver_commission: 15.00,
    status: 'delivered',
    total: 264.97,
    payment_method: 'qr',
    qr_code_data: null,
    created_at: daysAgo(10),
    paid_at: daysAgo(10),
    delivered_at: daysAgo(6),
    cancelled_at: null,
    cancellation_reason: null,
    internal_notes: null,
    customer_name: 'Juan Operativo',
    customer_phone: '+591 75512345',
    customer_email: 'cliente@tacticos.bo',
    customer_address: 'Av. Villazón Km 3, Huayllani, Sacaba, Cochabamba',
    delivery_notes: null,
    customer_rating: 4,
    customer_review: 'Buen servicio motorizado a Sacaba, llegó puntual.'
  },
  {
    id: 'ord-007',
    user_id: 'client-01',
    vendor_id: null,
    driver_id: null,
    shipping_zone_id: 'zone-07',
    shipping_cost: 35.00,
    driver_commission: 25.00,
    status: 'preparing',
    total: 504.98,
    payment_method: 'qr',
    qr_code_data: null,
    created_at: daysAgo(0),
    paid_at: daysAgo(0),
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    internal_notes: 'En empaque de equipo especial para despacho por Flota a Santa Cruz.',
    customer_name: 'Fernando Paz',
    customer_phone: '+591 72244668',
    customer_email: 'fernando@tacticos.bo',
    customer_address: 'Terminal Bimodal Santa Cruz de la Sierra (Despacho desde Terminal Cbba)',
    delivery_notes: 'Enviar guía de encomienda escaneada por WhatsApp.',
    customer_rating: null,
    customer_review: null
  },
  {
    id: 'ord-008',
    user_id: 'client-01',
    vendor_id: null,
    driver_id: null,
    shipping_zone_id: 'zone-06',
    shipping_cost: 18.00,
    driver_commission: 13.00,
    status: 'pending',
    total: 177.98,
    payment_method: 'qr',
    qr_code_data: 'QR-SESSION-008',
    created_at: daysAgo(0),
    paid_at: null,
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    internal_notes: null,
    customer_name: 'Juan Operativo',
    customer_phone: '+591 75512345',
    customer_email: 'cliente@tacticos.bo',
    customer_address: 'Av. Ecológica #450, Tiquipaya, Cochabamba',
    delivery_notes: null,
    customer_rating: null,
    customer_review: null
  },
];

export const demoOrderItems: OrderItem[] = [
  { id: 'oi-001', order_id: 'ord-001', product_id: 'prod-01', quantity: 1, unit_price: 340.00, subtotal: 340.00 },
  { id: 'oi-002', order_id: 'ord-001', product_id: 'prod-05', quantity: 1, unit_price: 120.00, subtotal: 120.00 },
  { id: 'oi-003', order_id: 'ord-002', product_id: 'prod-03', quantity: 1, unit_price: 380.00, subtotal: 380.00 },
  { id: 'oi-004', order_id: 'ord-003', product_id: 'prod-04', quantity: 1, unit_price: 220.00, subtotal: 220.00 },
  { id: 'oi-005', order_id: 'ord-003', product_id: 'prod-05', quantity: 1, unit_price: 120.00, subtotal: 120.00 },
  { id: 'oi-006', order_id: 'ord-004', product_id: 'prod-04', quantity: 1, unit_price: 220.00, subtotal: 220.00 },
  { id: 'oi-007', order_id: 'ord-006', product_id: 'prod-02', quantity: 1, unit_price: 310.00, subtotal: 310.00 },
  { id: 'oi-008', order_id: 'ord-006', product_id: 'prod-05', quantity: 1, unit_price: 120.00, subtotal: 120.00 },
  { id: 'oi-009', order_id: 'ord-007', product_id: 'prod-01', quantity: 1, unit_price: 340.00, subtotal: 340.00 },
  { id: 'oi-010', order_id: 'ord-007', product_id: 'prod-02', quantity: 1, unit_price: 310.00, subtotal: 310.00 },
  { id: 'oi-011', order_id: 'ord-008', product_id: 'prod-09', quantity: 2, unit_price: 145.00, subtotal: 290.00 },
  { id: 'oi-012', order_id: 'ord-009', product_id: 'prod-01', quantity: 1, unit_price: 340.00, subtotal: 340.00 },
  { id: 'oi-013', order_id: 'ord-009', product_id: 'prod-10', quantity: 1, unit_price: 180.00, subtotal: 180.00 },
  { id: 'oi-014', order_id: 'ord-010', product_id: 'prod-05', quantity: 1, unit_price: 120.00, subtotal: 120.00 },
];

// ============ PAYMENT VERIFICATIONS ============
export const demoPayments: PaymentVerification[] = [
  { id: 'pv-001', order_id: 'ord-001', qr_session_id: 'qs-001', device_id: 'mobile-vendor', status: 'verified', verified_at: daysAgo(28), notification_sent_at: daysAgo(28), notification_error: null, verified_by: 'vendor-01', created_at: daysAgo(28) },
  { id: 'pv-002', order_id: 'ord-002', qr_session_id: 'qs-002', device_id: 'mobile-vendor', status: 'verified', verified_at: daysAgo(25), notification_sent_at: daysAgo(25), notification_error: null, verified_by: 'vendor-01', created_at: daysAgo(25) },
  { id: 'pv-003', order_id: 'ord-003', qr_session_id: 'qs-003', device_id: 'mobile-vendor', status: 'verified', verified_at: daysAgo(20), notification_sent_at: daysAgo(20), notification_error: null, verified_by: 'vendor-01', created_at: daysAgo(20) },
  { id: 'pv-004', order_id: 'ord-004', qr_session_id: 'qs-004', device_id: 'mobile-vendor', status: 'verified', verified_at: daysAgo(15), notification_sent_at: daysAgo(15), notification_error: null, verified_by: 'vendor-01', created_at: daysAgo(15) },
  { id: 'pv-005', order_id: 'ord-006', qr_session_id: 'qs-006', device_id: 'mobile-vendor', status: 'verified', verified_at: daysAgo(10), notification_sent_at: daysAgo(10), notification_error: null, verified_by: 'vendor-01', created_at: daysAgo(10) },
  { id: 'pv-006', order_id: 'ord-007', qr_session_id: 'qs-007', device_id: 'mobile-vendor', status: 'verified', verified_at: daysAgo(5), notification_sent_at: daysAgo(5), notification_error: null, verified_by: 'vendor-01', created_at: daysAgo(5) },
  { id: 'pv-007', order_id: 'ord-008', qr_session_id: 'qs-008', device_id: null, status: 'pending', verified_at: null, notification_sent_at: null, notification_error: null, verified_by: null, created_at: daysAgo(2) },
  { id: 'pv-008', order_id: 'ord-009', qr_session_id: 'qs-009', device_id: null, status: 'pending', verified_at: null, notification_sent_at: null, notification_error: null, verified_by: null, created_at: daysAgo(1) },
  { id: 'pv-009', order_id: 'ord-010', qr_session_id: 'qs-010', device_id: null, status: 'pending', verified_at: null, notification_sent_at: null, notification_error: null, verified_by: null, created_at: daysAgo(0) },
];

// ============ AUDIT LOGS ============
export const demoAuditLogs: AuditLog[] = [
  { id: 'al-001', user_id: 'admin-01', action: 'INSERT', entity: 'products', entity_id: 'prod-01', before: null, after: { name: 'Plate Carrier Táctico Nivel IV Multicam', price: 340.00, cost_price: 250.00 }, ip: '192.168.1.10', user_agent: 'Mozilla/5.0', created_at: daysAgo(30) },
  { id: 'al-002', user_id: 'vendor-01', action: 'UPDATE', entity: 'products', entity_id: 'prod-09', before: { stock: 45 }, after: { stock: 38 }, ip: '192.168.1.15', user_agent: 'Mozilla/5.0', created_at: daysAgo(5) },
  { id: 'al-003', user_id: 'vendor-01', action: 'UPDATE', entity: 'orders', entity_id: 'ord-003', before: { status: 'paid' }, after: { status: 'shipped' }, ip: '192.168.1.15', user_agent: 'Expo/Mobile', created_at: daysAgo(18) },
  { id: 'al-004', user_id: 'admin-01', action: 'UPDATE', entity: 'user_roles', entity_id: 'vendor-01', before: { role: 'client' }, after: { role: 'vendor' }, ip: '192.168.1.10', user_agent: 'Mozilla/5.0', created_at: daysAgo(60) },
  { id: 'al-005', user_id: 'vendor-01', action: 'UPDATE', entity: 'payment_verifications', entity_id: 'pv-006', before: { status: 'pending' }, after: { status: 'verified' }, ip: '192.168.1.15', user_agent: 'Expo/Mobile', created_at: daysAgo(5) },
];

// ============ SYSTEM ALERTS ============
export const demoAlerts: SystemAlert[] = [
  { id: 'sa-001', type: 'low_stock', severity: 'critical', message: 'Mira Holográfica EOTech XPS3 — Stock crítico: 2 unidades en almacén Cbba', resolved: false, resolved_by: null, created_at: daysAgo(1), resolved_at: null },
  { id: 'sa-002', type: 'low_stock', severity: 'warning', message: 'Reloj Militar Digital G-Shock — Stock bajo: 5 unidades (umbral: 5)', resolved: false, resolved_by: null, created_at: daysAgo(2), resolved_at: null },
  { id: 'sa-003', type: 'pending_payment', severity: 'warning', message: 'Orden ORD-008 sin verificar por más de 48 horas', resolved: false, resolved_by: null, created_at: daysAgo(0), resolved_at: null },
  { id: 'sa-004', type: 'low_stock', severity: 'info', message: 'Botas Desert Storm restockeadas exitosamente en almacén Central', resolved: true, resolved_by: 'admin-01', created_at: daysAgo(10), resolved_at: daysAgo(10) },
];

// ============ NOTIFICATIONS ============
export const demoNotifications: Notification[] = [
  { id: 'not-001', user_id: 'admin-01', title: 'Nuevo pedido recibido', body: 'Orden #ORD-010 por Bs. 120.00 — Juan Táctico (Cochabamba)', type: 'order', read: false, link: '/admin/sales', created_at: daysAgo(0) },
  { id: 'not-002', user_id: 'admin-01', title: 'Stock bajo', body: 'Mira Holográfica XPS3 tiene solo 2 unidades', type: 'alert', read: false, link: '/admin/products', created_at: daysAgo(1) },
  { id: 'not-003', user_id: 'admin-01', title: 'Pago verificado', body: 'Orden #ORD-007 verificada — Bs. 685.00 (Envío a Terminal)', type: 'payment', read: true, link: '/admin/payments', created_at: daysAgo(5) },
];

// ============ METRICS ============
export const demoDailySales: DailySalesSummary[] = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(now.getTime() - (29 - i) * 86400000).toISOString().split('T')[0],
  total_sales: Math.round((Math.random() * 800 + 200) * 100) / 100,
  order_count: Math.floor(Math.random() * 8 + 1),
  avg_ticket: Math.round((Math.random() * 200 + 50) * 100) / 100,
  unique_customers: Math.floor(Math.random() * 6 + 1),
}));

export const demoProductSales: ProductSalesSummary[] = demoProducts.map(p => ({
  product_id: p.id,
  product_name: p.name,
  category_id: p.category_id || '',
  total_sold: Math.floor(Math.random() * 50 + 5),
  total_revenue: Math.round((Math.random() * 5000 + 500) * 100) / 100,
  order_count: Math.floor(Math.random() * 30 + 3),
})).sort((a, b) => b.total_revenue - a.total_revenue);

export const demoCategorySales: CategorySalesSummary[] = demoCategories.map(c => ({
  category_id: c.id,
  category_name: c.name,
  total_sales: Math.round((Math.random() * 10000 + 1000) * 100) / 100,
  order_count: Math.floor(Math.random() * 40 + 5),
}));

// ============ FIXED AMOUNT QR MATRIX (ImgBB & SUPABASE) ============
// QRs estáticos pre-generados de 3+ años con monto específico y QR comodín sin monto
export const demoFixedAmountQRs: FixedAmountQR[] = [
  {
    id: 'qr-001',
    amount: 50.00,
    qr_image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80',
    bank_name: 'Banco Unión (Simple QR)',
    account_name: 'Tienda Táctica Bolivia SRL',
    is_active: true,
    is_default: false,
    expiration_years: '3 años',
    notes: 'QR estático oficial para abonos exactos de Bs. 50.00',
    created_at: daysAgo(60),
  },
  {
    id: 'qr-002',
    amount: 100.00,
    qr_image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80',
    bank_name: 'Banco Unión (Simple QR)',
    account_name: 'Tienda Táctica Bolivia SRL',
    is_active: true,
    is_default: false,
    expiration_years: '3 años',
    notes: 'QR estático para órdenes de Bs. 100.00',
    created_at: daysAgo(60),
  },
  {
    id: 'qr-003',
    amount: 150.00,
    qr_image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80',
    bank_name: 'Banco Mercantil Santa Cruz',
    account_name: 'Tienda Táctica Bolivia SRL',
    is_active: true,
    is_default: false,
    expiration_years: '3 años',
    notes: 'QR estático para órdenes de Bs. 150.00',
    created_at: daysAgo(50),
  },
  {
    id: 'qr-004',
    amount: 200.00,
    qr_image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80',
    bank_name: 'Banco Nacional de Bolivia (BNB)',
    account_name: 'Tienda Táctica Bolivia SRL',
    is_active: true,
    is_default: false,
    expiration_years: '3 años',
    notes: 'QR estático para órdenes de Bs. 200.00',
    created_at: daysAgo(40),
  },
  {
    id: 'qr-005',
    amount: 350.00,
    qr_image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80',
    bank_name: 'Banco de Crédito de Bolivia (BCP)',
    account_name: 'Tienda Táctica Bolivia SRL',
    is_active: true,
    is_default: false,
    expiration_years: '3 años',
    notes: 'QR estático para combos y chalecos de Bs. 350.00',
    created_at: daysAgo(30),
  },
  {
    id: 'qr-default',
    amount: null,
    qr_image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80',
    bank_name: 'Simple QR Bolivia (Multibanco)',
    account_name: 'Tienda Táctica Bolivia SRL',
    is_active: true,
    is_default: true,
    expiration_years: 'Sin expiración (Estático)',
    notes: 'QR comodín sin monto fijo. Si el total de la orden no coincide con un QR pre-generado, se muestra este QR para que el cliente digite el monto manualmente.',
    created_at: daysAgo(90),
  },
];
